### ISSUE TITLE
Provide Pipenv in the base image

### ISSUE THREAD

**Issue by fridex** [thoth-station/s2i-thoth#11]
It would be probably nice to ship Pipenv in the container image as we will always use Pipenv to install packages. This way we will have control of the pipenv release which is used.

**Comment by fridex** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ship s2i-thoth-* container images with Pipenv installed](https://trello.com/c/ke43ENdR/717-ship-s2i-thoth-container-images-with-pipenv-installed)

**Comment by goern** [comment]
@fridex has this been implemented with https://github.com/thoth-station/s2i-thoth/commit/7298a565ce94147ba26cc2b7dd243c140fedc197 ?

**Comment by fridex** [comment]
yes. closing...
