### ISSUE TITLE
Modify s2i-thoth to get supported with the redhat cpaas 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-thoth#124]
**Is your feature request related to a problem? Please describe.**
we would like to get s2i-thoth image to be built with the RedHat cpaas (continuous production as a service) so that it can be a viable option for other products either to be built upon or to use as the base image. 
The cpaas requires the repository to be configured in a specific manner.
Due the internal build service all build time external calls are to be modified or removed.
For Example:
https://github.com/thoth-station/s2i-thoth/blob/master/ubi8-py36/Dockerfile#L33

**Describe the solution you'd like**
Replace all curl calls with direct calls.

**Comment by fridex** [comment]
Can we use packages from PyPI (thamos, micropipenv, ...) or do they need to be packaged as RPMs?

**Comment by harshad16** [comment]
Based on the documentation of cpaas and osbs, 
It seems that the dockerfile to be built is to be present on the root directory. https://osbs.readthedocs.io/en/latest/users.html#writing-a-dockerfile

In this way, we would have to restructure the whole repository. 
maybe we can fork a downstream repo and work on a single image as s2i-thoth-ubi8-py36

will confirm the requirement of the dockerfile for the build.

**Comment by fridex** [comment]
thanks, @harshad16! :+1:

**Comment by harshad16** [comment]
> Can we use packages from PyPI (thamos, micropipenv, ...) or do they need to be packaged as RPMs?

osbs build checks use source integration (ex: cachito) , which handles module and source code. 
will take help from the datahub team to investigate these installations.

however, from the documentation it seems that cachito doesn't support python: 
https://gitlab.cee.redhat.com/cpaas/documentation/-/blob/master/users/midstream/usrc_updater.adoc#user-content-cachito

**Comment by harshad16** [comment]
cachito supports pip package manager. 
https://source.redhat.com/groups/public/container-build-system/container_build_system_wiki/containers_from_source_multistage_builds_in_osbs#jive_content_id_Cachito_Integration_for_pip

**Comment by harshad16** [comment]
Closing this issue.
rhods has forked our repo and added additional bits for cpaas build.
https://github.com/red-hat-data-services/s2i-thoth
