### ISSUE TITLE
latest version v0.24.1 is missing all the packages 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-thoth#133]
**Describe the bug**
The latest version s2i-thoth version [v0.24.1](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.24.1&tab=tags) is missing the required packages from it, for example : `thamos`

```
> podman run -it quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.24.1 bash
> (app-root) thamos
bash: thamos: command not found
```

**Environment variables used for s2i configuration**

List of *THAMOS_** and *THOTH_** environment variables from the build config:
```
(app-root) env
THAMOS_NO_PROGRESSBAR=1
THOTH_S2I_NAME=quay.io/thoth-station/s2i-thoth-ubi8-py36
LANG=en_US.UTF-8
SUMMARY=Thoth's Source-to-Image for Python 3.6 applications
STI_SCRIPTS_URL=image:///usr/libexec/s2i
DESCRIPTION=Thoth's Source-to-Image for Python 3.6 applications. This toolchain is based on Red Hat UBI8. It includes pipenv.
PYTHONIOENCODING=UTF-8
VIRTUAL_ENV=/opt/app-root
THAMOS_NO_EMOJI=1
PYTHON_VERSION=3.6
STI_SCRIPTS_PATH=/usr/libexec/s2i
APP_ROOT=/opt/app-root
THOTH_S2I_VERSION=0.24.1
```

**Comment by harshad16** [comment]
micropipenv could read from the requirements.txt. Seems issue with the requirements.txt format: https://github.com/thoth-station/s2i-thoth/blob/master/requirements.txt
caused by commit: https://github.com/thoth-station/s2i-thoth/commit/4b9f41da99c72efcc898dba2248065722ca80da2

**Comment by fridex** [comment]
Thanks. This should be handled by Kevin's bugfix https://github.com/thoth-station/kebechet/pull/686. A new Kebechet needs to be released.

**Comment by goern** [comment]
is this still valide for v0.25.1 ?

**Comment by harshad16** [comment]
No this is not valid for newer versions.
closing the issue.
