### ISSUE TITLE
thamos not working in some of the recent s2i-thoth version

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-thoth#134]
**Describe the bug**

The following versions of the s2i-thoth ubi8-py36 fails to execute `thamos` cli:
[v0.24.0](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.24.0&tab=tags)
[v0.23.2](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.23.2&tab=tags)
[v0.23.1](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.23.1&tab=tags)
[v0.23.0](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.23.0&tab=tags)

due to missing required packages **dataclasses**, **idna-ssl**, **importlib-metadata**.

**Comment by harshad16** [comment]
noticed this because of the requirements installed in the container. 
As dataclasses is not needed for py38, it is not included in the requirements.txt, which causes in the run of thamos in ubi8-py3.6 env.

a possible solution can be:
- instead of installing from pinned requirements.txt, use the requirements.in 
- maintain separate requirements based on environments.

**Comment by fridex** [comment]
> As dataclasses is not needed for py38, it is not included in the requirements.txt, which causes in the run of thamos in ubi8-py3.6 env.

Nice catch! This is somehow bad for us if we want to pin the versions. Ideally having overlays and let kebechet operate on the lock files in the nested directories. As we are not quite there yet, we could keep requirements.txt unpinned. The main reason I did that was to make sure we get updates from kebechet on new thoth tooling releases.

**Comment by harshad16** [comment]
Should have individual requirements.txt in the environment and then point that in the respective Dockerfile? In this way, we would not break the requirements based on the python version?

**Comment by fridex** [comment]
> Should have individual requirements.txt in the environment and then point that in the respective Dockerfile? In this way, we would not break the requirements based on the python version?

Yes, that would work :+1: I think that's the proper way of doing it as we have different Python versions in these container images. Sadly the repo will not be managed by Kebechet as we do not support nested lock files yet.

**Comment by fridex** [comment]
@harshad16 can we close this or should this be kept?

**Comment by harshad16** [comment]
This issue is fixed with the release of the [v0.24.2](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tag=v0.24.0&tab=tags)
thanks for all the thoughts.
