### ISSUE TITLE
unsetting THOTH_CONFIG_CHECK fails the build when config is not present

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-thoth#166]
**Describe the bug**
Setting `THOTH_CONFIG_CHECK=0` is still breaking build with thoth config not found error. as we know when setting this [THOTH_CONFIG_CHECK](https://github.com/thoth-station/s2i-thoth/blob/d7e70ae9f47ef4a4ebd483a229c3c6575397d2c2/assemble#L13)=0, it also required to set this THOTH_ERROR_FALLBACK=1.

however the build would still break, the install is done via thamos which is a request/looking up for thoth config file.
https://github.com/thoth-station/s2i-thoth/blob/d7e70ae9f47ef4a4ebd483a229c3c6575397d2c2/ubi8-py38/s2i_assemble.patch#L85

https://github.com/thoth-station/thamos/blob/003f6a22c411fba48566f2e9fc5c93dbf2be17be/thamos/lib.py#L991

**Environment variables used for s2i configuration**

List of *THAMOS_** and *THOTH_** environment variables from the build config:
``` 
        - name: THAMOS_RUNTIME_ENVIRONMENT
        - name: ENABLE_MICROPIPENV
          value: '1'
        - name: THOTH_DRY_RUN
          value: '1'
        - name: THOTH_CONFIG_CHECK
          value: '0'
        - name: THOTH_ADVISE
          value: '0'
        - name: THOTH_PROVENANCE_CHECK
          value: '0'
        - name: THOTH_ERROR_FALLBACK
          value: '1'
```
**Expected behavior**
successfully executing without thoth config file.

**Build Log**
```
>>> Thoth advises are not activated
>>> Restoring previous requirements lock as THOTH_DRY_RUN was set
~
---> Installing application source ...
2021-04-15 18:31:42,291 [25] DEBUG    thamos: Debug mode turned on
2021-04-15 18:31:42,292 [25] DEBUG    thamos: Thamos version: '1.16.0'
2021-04-15 18:31:42,297 [25] CRITICAL root: Traceback (most recent call last):
  File "/opt/app-root/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 409, in install
    runtime_environment_name=runtime_environment, dev=dev, pip_args=pip_args
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 936, in install
    "pipenv" if thoth_config.requirements_format == "pipenv" else "requirements"
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 179, in requirements_format
    requirements_format = self.content.get("requirements_format") or "pipenv"
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 172, in content
    self.load_config()
  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 277, in load_config
    with workdir(config.CONFIG_NAME):
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/app-root/lib/python3.6/site-packages/thamos/utils.py", line 53, in workdir
    f"No {file_lookup} found in the current directory {os.getcwd()!r} or in any of its parent "
thamos.exceptions.NoProjectDirError: No .thoth.yaml found in the current directory '/opt/app-root/src' or in any of its parent directories, you can generate it using '/opt/app-root/bin/thamos config'
```

**Comment by fridex** [comment]
One way to fix this is to make thoth config mandatory in thoth s2i. `.thoth.yaml` holds information about requirements format that is used in thamos (hence thamos install requires thoth config being present). We could issue raw micropipenv as it is available, but that can introduce misleading installations.

An example of such misleading installation that can occur: requirements format is set to pip but Pipfile/Pipfile.lock are present, this way the build process uses pip requirements format (requirements.txt) when thoth.yaml is present. Now if the user turns off thoth features, and `micropipenv install` would be issued instead, it will pick Pipfile/Pipfile.lock based on priority. I think we could do this but with a warning printed when having this fallback scenario. WDYT?

**Comment by fridex** [comment]
Not providing `.thoth.yaml` complicates things and is prone to errors. I think it would be better to make Thoth configuration when using Thoth s2i mandatory. We can add a note to docs. wdyt?

**Comment by fridex** [comment]
@harshad16 ^^

**Comment by harshad16** [comment]
The benefits of `.thoth.yaml` are definitely there as you stated with that example.
we can state in the doc that it is mandatory requirement and include note in docs.

I think users are facing this when they simply wanna use micropipenv, we can define that if the only micropipenv is to be leverage, use the simple s2i-python image as it includes it already, however, we recommend on s2i-thoth with `.thoth.yaml` for a recommendation from thoth station engine which looks over different security factor before recommending packages.


Confusion raised as we had THOTH_CONFIG_CHECK=0 option still we were checking. 
maybe stating that this is deprecated and we require users to include .thoth.yaml if using s2i-thoth would suffice this particular issue.
WDYT?

**Comment by fridex** [comment]
Sounds good, tried to summarize this in #172, PTAL.
