### ISSUE TITLE
UBI/RHEL 9 based solvers

### ISSUE THREAD

**Issue by fridex** [thoth-station/s2i-thoth#234]
**Is your feature request related to a problem? Please describe.**

Let's monitor release cycle of UBI/RHEL 9 and provide relevant solvers to the deployment once they are available and ready to be used.

**Comment by codificat** [comment]
Related: https://github.com/thoth-station/core/issues/342

**Comment by fridex** [comment]
@Gregory-Pereira worked on a similar item in https://github.com/thoth-station/s2i-thoth/issues/231, related docs:

* https://github.com/thoth-station/s2i-thoth#updating-and-releasing-new-container-images
* https://github.com/thoth-station/thoth-application/blob/master/docs/thoth_s2i_procedure.md

The procedure is very similar, we need to wait for a stable UBI/RHEL 9 Python s2i.

**Comment by Gregory-Pereira** [comment]
I will go ahead and take a look at this as well.
/assign

**Comment by fridex** [comment]
> I will go ahead and take a look at this as well.

Thanks 💯 Worth checking the current state of UBI/RHEL 9 Python s2i. If they are considered stable, we should wait.

**Comment by fridex** [comment]
@frenzymadness, could you please let us know the current state for UBI 9 Python s2i? What is its state and when it could become stable? Thanks in advance.

**Comment by frenzymadness** [comment]
Hi. UBI9 is still beta and we haven't started building our Python container image on top of that yet. We are currently working on Centos stream 9: https://github.com/sclorg/s2i-python-container/pull/501 But there are some blockers.

I see the image in the catalog: https://catalog.redhat.com/software/containers/ubi9-beta/ubi/60a6ea70f13ea7781b9fd615?container-tabs=gti

But I also cannot pull it:
```
Trying to pull registry.access.redhat.com/ubi9-beta/ubi:9.0.0beta-892...
Error: Source image rejected: None of the signatures were accepted, reasons: Invalid GPG signature: gpgme.Signature{Summary:128, Fingerprint:"938A80CAF21541EB",…
```

**Comment by fridex** [comment]
Thanks, @frenzymadness. We will wait for the stable release then. Thanks again 👍🏻 

/lifecycle frozen

**Comment by goern** [comment]
@codificat could you work with @Gregory-Pereira on this? thx!

**Comment by harshad16** [comment]
A new image is available now:
https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?tag=1-59&push_date=1656417750000
probably time to re-visit this.

**Comment by frenzymadness** [comment]
We are working on Python container image based on UBI 9: https://github.com/sclorg/s2i-python-container/pull/528

My estimation is that it should be finished this week.
