### ISSUE TITLE
fedora35-py3.10 build for v0.33.0 has failed the build

### ISSUE THREAD

**Issue by harshad16** [thoth-station/s2i-thoth#242]
fedora35-py3.10 build for v0.33.0 has failed the build with following error message:

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/tmp/tmp.2vBvyYm7DX
curl: (6) getaddrinfo() thread failed to start
curl: (6) getaddrinfo() thread failed to start
```

**Comment by harshad16** [comment]
curl in fedora35 is having issues

https://bugzilla.redhat.com/show_bug.cgi?id=2042582
https://pascalroeleven.nl/2021/09/09/ubuntu-21-10-and-fedora-35-in-docker/

**Comment by harshad16** [comment]
@fridex  @codificat any suggestion on how should be tackling this?

**Comment by goern** [comment]
/kind bug
/priority critical-urgent

is this worth a prescription?
/sig stack-guidance

**Comment by harshad16** [comment]
> is this worth a prescription? 

I m not sure, as this is a binary (curl) having issues, don't know if this would fit for our python prescriptions.

**Comment by codificat** [comment]
> curl in fedora35 is having issues
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2042582

If I understand this correctly, this happens with Docker running on RHEL7.

I did not have problems in a quick test running curl inside a container on my local F35 laptop...

> fedora35-py3.10 build for v0.33.0 has failed the build with following error message:

Where is that build running? Do we have more details about the host running the container?
Can this run elsewhere?

**Comment by harshad16** [comment]
> Where is that build running? Do we have more details about the host running the container? Can this run elsewhere?

It is built directly in quay.
https://quay.io/repository/thoth-station/s2i-thoth-f35-py310?tab=builds

**Comment by codificat** [comment]
> > Where is that build running? Do we have more details about the host running the container?
> 
> It is built directly in quay. https://quay.io/repository/thoth-station/s2i-thoth-f35-py310?tab=builds

So, maybe file an issue with quay? https://issues.redhat.com/projects/PROJQUAY/issues/

> > Can this run elsewhere?
> 
> Not sure.

It builds on my laptop (yeah, containers were going to fix that situation... oh well)

Maybe a workaround could be to build/push it manually while waiting for feedback from the quay team?

**Comment by harshad16** [comment]
Further going over this with new version v0.34.0 , it is stil failing to update.
```
Collecting setuptools==63.1.0
  Downloading setuptools-63.1.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 32.4 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
ERROR: Cannot uninstall setuptools 57.4.0, RECORD file not found. Hint: The package was installed by rpm.
```

**Comment by harshad16** [comment]
The build is now fixed: https://quay.io/repository/thoth-station/s2i-thoth-f35-py310
closing this
thanks, everyone for help.
