### ISSUE TITLE
Use micropipenv as a wrapper for all dependency formats

### ISSUE THREAD

**Issue by fridex** [thoth-station/s2i-thoth#47]
**Is your feature request related to a problem? Please describe.**

As of now, we run micropipenv only if Pipfile is present in the application root - this means micropipenv installation method discovery installs dependencies from Poetry files only if Pipenv.lock is not present and poetry.lock+pyproject.toml are present. A similar thing applies to requirements.txt file - Pipenv+requirements.txt have to be present and poetry.lock, Pipfile.lock not:

https://github.com/thoth-station/s2i-thoth/blob/f5eb71398bd5be34dd6d75def50e0aabb10c1db8/ubi8-py36/s2i_assemble.patch#L29-L36

**Describe the solution you'd like**

Promote micropipenv to be a wrapper for all installation methods available as originally designed. We don't need to obey ENABLE_PIPENV environment in that case.

**Additional context**

The assemble patch will need to be adjusted to respect this. Let's wait for Python maint and possible inclusion of micropipenv into the official Python s2i.

**Comment by goern** [comment]
is this done?!

**Comment by fridex** [comment]
Yes with the current patch applied to Python s2i.
