### ISSUE TITLE
s2i build not activating Thoth

### ISSUE THREAD

**Issue by crobby** [thoth-station/s2i-thoth#6]
I have some source with all of the Thoth env variables set and my project includes a .thoth file, but when I do the s2i build process, it never seems to activate Thoth.  Instead, it just processes my Pipfile normally and goes about the build.  Is there another step I need in this process so that Thoth will run?

Here is my .s2i/environment file contents:
```
MODEL_NAME=detect_anomaly
API_TYPE=REST
SERVICE_TYPE=MODEL
PERSISTENCE=0
# Enable Pipenv in OpenShift's s2i.
ENABLE_PIPENV="1"
# Force use Thoth service.
THOTH_ADVISE="1"
# Set to 1 if you would like to submit stack to Thoth but not use
# the recommended stack - Pipfile.lock from the Git repo will be
# used.
THOTH_DRY_RUN="0"
# .thoth.yaml file is generated from template file
# thoth_conf_template.yaml
THAMOS_CONFIG_TEMPLATE="thoth_conf_template.yaml"
# Enable expansion based on environment variables when generating
# .thoth.yaml file - this needs to be explicitly turned on due to
# possible security implications.
THAMOS_CONFIG_EXPAND_ENV="1"
# Do not use cached results, always force analysis on Thoth's side
# if set to 1.
THAMOS_FORCE="0"
# Run thamos in verbose mode to show what's going on.
THAMOS_VERBOSE="1"
# The adviser on Thoth's backend side is run in debug mode, you can
# obtain logs by running thamos logs <analysis id> or directly on
# Thoth's user API (the analysis id gets printed into the console
# during the build process in OpenShift).
THAMOS_DEBUG="1"
# Thoth deployment to be used - pass just host, API discovery is
# performed by Thamos.
THOTH_HOST="khemenu.thoth-station.ninja"
# Use latest sources of Thamos and Invectio from Git master.
THOTH_FROM_MASTER="0"
```

**Comment by fridex** [comment]
Cannot reproduce this issue on my own. Could you post a link to the repo to test this build?

One thing that caught my eye:

```
THAMOS_CONFIG_TEMPLATE="thoth_conf_template.yaml"
```

Do you use `.thoth.yaml` in the repo or template?

**Comment by crobby** [comment]
actually, thoth_conf_template.yaml is unused (was an artifact of copy/paste).
I did get farther along in the process by using quay.io/thoth-station/s2i-thoth-ubi8-py36 as my base image, but still ran into problems.  I will push what I have up to a fork in my repo so you can take a closer look.

**Comment by crobby** [comment]
https://gitlab.com/crobby/ai-library/tree/thoth  is the branch where I have my changes.  each model is in a separate folder.  The directories that I've tried to build are: anomaly_detection (which seems to die because one of the packages is being installed form github rather than a pypi package) and  associative_rule_learning (which seems to die when installing googleapis-common-protos).

**Comment by goern** [comment]
@fridex PTAL

**Comment by goern** [comment]
is this still valid?!

**Comment by fridex** [comment]
Sorry, I somehow missed this. Is this still valid with the most recent s2i-thoth images (e.g. quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.13.0)?
