### ISSUE TITLE
Start using micropipenv from rpm

### ISSUE THREAD

**Issue by fridex** [thoth-station/s2i-thoth#75]
**Is your feature request related to a problem? Please describe.**

As micropipenv is a tooling that is shipped with the builder s2i container image, we should install it using [rpm package](https://koji.fedoraproject.org/koji/packageinfo?packageID=micropipenv).

**Describe the solution you'd like**

Install micropipenv from [rpm](https://koji.fedoraproject.org/koji/packageinfo?packageID=micropipenv), not from PyPI as a [Python package](https://pypi.org/project/micropipenv/).

**Comment by fridex** [comment]
Why was this closed?

**Comment by goern** [comment]
uhh, because I looked at the toolbox, which is using micropipenv from rpm.. sorry

**Comment by fridex** [comment]
We can close this one as we integrated micropipenv to thamos, see https://github.com/thoth-station/s2i-thoth/issues/90
