### ISSUE TITLE
Thoth s2i image is missing psql

### ISSUE THREAD

**Issue by vpavlin** [thoth-station/s2i-thoth#78]
**Describe the bug**
We are trying move to Thoth s2i base images, but JupyterHub container will fail to start as it is trying to use `psql` command which is not available in the Thoth image.

```
/opt/app-root/bin/wait-for-database: line 8: psql: command not found
```

**Environment variables used for s2i configuration**

List of *THAMOS_** and *THOTH_** environment variables from the build config:

**Expected behavior**
`wait-for-database`  script succeeds and the container starts

**Actual behavior**
the script fails and the image errors out over time

**Additional context**
It works fine with `registry.access.redhat.com/ubi7/python-36` base image

**Build log**

**Comment by fridex** [comment]
> It works fine with `registry.access.redhat.com/ubi7/python-36` base image

Which s2i-thoth container image are you using? We don't have ubi7 alternatives.

**Comment by fridex** [comment]
> > It works fine with `registry.access.redhat.com/ubi7/python-36` base image
> 
> Which s2i-thoth container image are you using? We don't have ubi7 alternatives.

Checked all the available s2i-thoth we provide, none of them is shipped with psql. Base container images are not shipped with psql -- we base on s2i fedora{31,32}/ubi8 container images and install just our tooling into them. Would you mind creating your own container image with psql based on s2i-thoth?

**Comment by vpavlin** [comment]
Yeah, I checked the ubi8/python-36 and it seems like they removed the psql...I call that a regression:) I'll stick with the ubi7 image for now and create an issue to come up with the new base image later.
