### ISSUE TITLE
investigate how OSBS/Fedora Build Service uses s2i [9pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-thoth#85]
Let's investigate how OSBS and https://docs.fedoraproject.org/en-US/containers/buildsys/ use s2i or tekton, and how to integrate with these...

**Comment by harshad16** [comment]
Based on the initial investigation it seems like the osbs builds require Dockerfile for the build process. https://osbs.readthedocs.io/en/latest/index.html
The internal RedHat Build service which uses the osbs build service can have more details, so will start investigating in there as well.

**Comment by goern** [comment]
@fridex @TomasTomecek
