### ISSUE TITLE
Add RPMs to install successfully ssdeep

### ISSUE THREAD

**Issue by pacospace** [thoth-station/s2i-thoth#86]
Recent changes in thoth-storages [1] required the introduction of ssdeep library [2]. 

Simple pipenv installs on Fedora 31 gives the following error:

pipenv version: `pipenv, version 2020.8.13`
Python version: `3.6`
```
✔ Successfully created virtual environment! 
Virtualenv location: /home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-toidkb2w/ssdeep/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-toidkb2w/ssdeep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info
     cwd: /tmp/pip-resolver-toidkb2w/ssdeep/
Complete output (102 lines):
running egg_info
creating /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info/ssdeep.egg-info
writing /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info/ssdeep.egg-info/PKG-INFO
writing dependency_links to /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info/ssdeep.egg-info/dependency_links.txt
writing requirements to /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info/ssdeep.egg-info/requires.txt
writing top-level names to /tmp/pip-resolver-toidkb2w/ssdeep/pip-egg-info/ssdeep.egg-info/top_level.txt
writing manifest file '/tmp/pip-resolver-toidkb2w/ssd
eep/pip-egg-info/ssdeep.egg-info/SOURCES.txt'
src/ssdeep/__pycache__/_ssdeep_cffi_a28e5628x27adcb8d.c:266:14: fatal error: fuzzy.h: No such file or directory
  266 |     #include "fuzzy.h"
      |              ^~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```
The installation on fedora OS requires:
`sudo dnf install libffi-devel python3-devel python3-pip ssdeep-devel ssdeep-libs` [3] to be successfull.

References:
- [1] https://github.com/thoth-station/storages/pull/2046 
- [2] https://python-ssdeep.readthedocs.io/en/latest/index.html
- [3] https://python-ssdeep.readthedocs.io/en/latest/installation.html#id11

**Comment by harshad16** [comment]
As pointed out, the **ssdeep** library needs development tool rpm packages to be installed in the base image.
as we use _thoth-s2i-ubi8_ image as a universal base for s2i container images, which require minimum requirements.
It feels like we should have a different base for thoth-storages as **ssdeep** file requirement might be required by other _thoth-s2i-ubi8_ users.

what are your thoughts on this? @pacospace  @fridex

**Comment by fridex** [comment]
> As pointed out, the **ssdeep** library needs development tool rpm packages to be installed in the base image.
> as we use _thoth-s2i-ubi8_ image as a universal base for s2i container images, which require minimum requirements.
> It feels like we should have a different base for thoth-storages as **ssdeep** file requirement might be required by other _thoth-s2i-ubi8_ users.
> 
> what are your thoughts on this? @pacospace @fridex

I see three options:

* add the native packages required to base s2i-thoth images - this is not nice as we claim s2i-thoth images are s2i with thoth addition
* create a base image specific for thoth - not nice as we need to maintain another set of images, on the other hand we can optimize base images (e.g. remove deps we do not want such as fortran) and include our native dependencies in the base
* build ssdeep wheel so that we will not need to build each time a container build is happening (can be a lot given the number of components that use thoth-storages)

I see 3. as the most viable solution. We can try to check if that's possible and reach out to upstream. Otherwise, we can try to check a similar hash or try to maintain a fork with wheel files built.

**Comment by pacospace** [comment]
> > As pointed out, the **ssdeep** library needs development tool rpm packages to be installed in the base image.
> > as we use _thoth-s2i-ubi8_ image as a universal base for s2i container images, which require minimum requirements.
> > It feels like we should have a different base for thoth-storages as **ssdeep** file requirement might be required by other _thoth-s2i-ubi8_ users.
> > what are your thoughts on this? @pacospace @fridex
> 
> I see three options:
> 
> * add the native packages required to base s2i-thoth images - this is not nice as we claim s2i-thoth images are s2i with thoth addition
> * create a base image specific for thoth - not nice as we need to maintain another set of images, on the other hand we can optimize base images (e.g. remove deps we do not want such as fortran) and include our native dependencies in the base
> * build ssdeep wheel so that we will not need to build each time a container build is happening (can be a lot given the number of components that use thoth-storages)
> 
> I see 3. as the most viable solution. We can try to check if that's possible and reach out to upstream. Otherwise, we can try to check a similar hash or try to maintain a fork with wheel files built.

Thanks!! Upstream seems a bit unmaintained though: https://github.com/DinoTools/python-ssdeep :/

**Comment by pacospace** [comment]
> Created wheel files in a separate fork for now:
> 
> https://pypi.org/project/thoth-ssdeep/#files
> 
> Wheels are built for py38 and py36 conforming to manylinux2014.

Thank you very much @fridex !!

**Comment by goern** [comment]
is this still valid?

@pacospace

**Comment by pacospace** [comment]
@fridex solved it creating `thoth-ssdeep` :) we can close it!
